### ISSUE TITLE
error when digitizing new feature

### ISSUE THREAD

**Issue by landam** [landam/grass-gis-git-migration-test#30]
**Reported by zanollim on 29 Jan 2008 10:27 UTC**
I have a simple polygon layer with some polygons.[if I try to digitize a new feature[[BR]([BR]]
Sometimes)]
(line, boundary, point or centroid) the feature is drawn[I have also this error:
```
Traceback (most recent call last):
  File "/usr/src/grass_trunk/dist.i686-pc-linux-gnu/etc/wx/gui_modules/mapdisp.py", line 812, in MouseActions
    self.OnLeftDown(event)
  File "/usr/src/grass_trunk/dist.i686-pc-linux-gnu/etc/wx/gui_modules/mapdisp.py", line 927, in OnLeftDown
    action="add")
  File "/usr/src/grass_trunk/dist.i686-pc-linux-gnu/etc/wx/gui_modules/dbm.py", line 2703, in __init__
    self.UpdateDialog(cat, queryCoords, qdist)
  File "/usr/src/grass_trunk/dist.i686-pc-linux-gnu/etc/wx/gui_modules/dbm.py", line 2892, in UpdateDialog
    nselected = self.mapDBInfo.SelectFromTable(layer, where="cat=%d" % self.cat)  File "/usr/src/grass_trunk/dist.i686-pc-linux-gnu/etc/wx/gui_modules/dbm.py", line 3138, in SelectFromTable
    value = self.tables[table]([BR]]
but)[name]['ctype'] (value)
ValueError: empty string for float()
```

Migrated-From: https://trac.osgeo.org/grass/ticket/30

**Comment by landam** [comment]
**Comment by martinl on 6 Feb 2008 13:11 UTC**
Now should be fixed in trunk, r29977. Can you reproduce problematic behaviour and confirm that it is fixed now?

Martin

**Comment by landam** [comment]
**Comment by zanollim on 11 Mar 2008 10:36 UTC**
ok fixed, now it seems work correctly.

Regards,
michele
